import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Space_Grotesk } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";

import SiteNavbar from "./components/SiteNavbar";
import Footer from "./components/Footer";


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const language = "en"; // Set the language code here
  return (
    <html className={`${inter.variable} ${spaceGrotesk.variable}`}>
      <body>
        <SiteNavbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
